Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600

  config.vm.define "app-server" do |app|
    app.vm.box = "ubuntu/jammy64"
    app.vm.hostname = "app-server"
    app.vm.boot_timeout = 600

    app.vm.network "private_network", ip: "192.168.56.10"
    app.vm.synced_folder "..", "/home/vagrant/PFE"

    app.vm.provider "virtualbox" do |vb|
      vb.name = "OETN-App-Server"
      vb.gui = false
      vb.memory = "3072"
      vb.cpus = 2
    end

    app.vm.provision "shell", path: "provision-docker.sh"
  end

  config.vm.define "monitoring-server" do |monitor|
    monitor.vm.box = "ubuntu/jammy64"
    monitor.vm.hostname = "monitoring-server"
    monitor.vm.boot_timeout = 600

    monitor.vm.network "private_network", ip: "192.168.56.11"
    monitor.vm.synced_folder "..", "/home/vagrant/PFE"

    monitor.vm.provider "virtualbox" do |vb|
      vb.name = "OETN-Monitoring-Server"
      vb.gui = false
      vb.memory = "3072"
      vb.cpus = 2
    end

    monitor.vm.provision "shell", path: "provision-docker.sh"
  end

end